---
title: "Revolution to Resistance: The Evolution of Iran's Security and Diplomatic Identity"
format: html
editor: visual
---

In "Revolution to Resistance: The Evolution of Iran's Security and Diplomatic Identity," we embark on a comprehensive journey through Iran's intricate historical tapestry, exploring how its varied past shapes its current stance in international affairs. This paper delves into the profound transformations that Iran has undergone, from the pivotal Safavid era to the revolutionary upheaval of 1979, which birthed the Islamic Republic under Ayatollah Ruhollah Khomeini. This journey is not just about shifts in political and religious landscapes; it is an exploration of Iran's evolving identity at the crossroads of Eastern traditions and Western influences.

The narrative unfolds by examining Iran's unique governance structure, where the intertwining of religion and politics under the Supreme Leader's authority forms the backbone of both domestic and international strategies. We scrutinize the pivotal role of the Islamic Revolutionary Guard Corps (IRGC) in shaping Iran's foreign policy and its complex interactions with regional and global powers, especially the United States and Israel. The paper also delves into the broader implications of Iran's cultural and cinematic representations, reflecting internal dynamics and contributing to its global image, particularly in the realm of human rights and gender equality.

At the heart of this analysis is Iran's strategic use of its oil resources, a critical element in its international relations and bargaining power, especially evident in the nuclear negotiations leading to the Joint Comprehensive Plan of Action (JCPOA). This multifaceted study reveals how Iran's historical experiences, ideological commitments, and strategic use of resources shape its national security posture and foreign policy, offering invaluable insights into the complexities of Middle Eastern politics and Iran's role within it.\

Revolution to Resistance: The Evolution of Iran's Security and Diplomatic Identity

By Yutong Jiang

\

Iran's journey through history has been a complex weave of religious conversions, cultural evolutions, and shifts in political power, which have positioned it as a regional leader where Eastern traditions meet Western influences. The Safavid era, particularly under Shah Ismail's reign beginning in 1501, was pivotal, transitioning Iran to a Twelver Shi'a Islamic state and expanding trade with Europe, notably the British Empire. The decline of this dynasty due to internal strife and external pressures, such as the Ottoman conflict, led to its dissolution in 1736, paving the way for societal upheaval and landmark events like the 1890 tobacco movement and the 1906 constitutional revolution . The transformative events of 1979, led by Ayatollah Ruhollah Khomeini, who ousted the Pahlavi dynasty, were instrumental in forming the Islamic Republic of Iran, ushering in a new era of religious, political, and social reconfiguration.

Iran's governance is characterized by the central authority of the Supreme Leader, who oversees the government, military, and judiciary, with the President managing state affairs under his directive. Legislative power resides with the Majles, and the Guardian Council ensures the adherence of laws and candidates to Islamic tenets. The Assembly of Experts, tasked with electing and overseeing the Supreme Leader, and the Expediency Council, which resolves legislative conflicts, complete the political structure. This system, born from the 1979 Islamic Revolution, shapes Iran's domestic and international strategies (Thaler 2010, 34-43).

Answering to the Supreme Leader, the Islamic Revolutionary Guard Corps (IRGC) wields significant influence over Iran's foreign policy, particularly through its support of proxy conflicts against Sunni-majority states, the U.S., and Israel. The 1970s' British withdrawal from the Middle East and the oil crisis created a strategic vacuum, rapidly filled by regional powers including Iran. The IRGC has supported groups like Hamas in Gaza and the Houthi rebels in Yemen---actions that directly conflict with U.S. and Israeli interests and escalate regional tensions. For instance, missile attacks attributed to the Houthis against Israel exemplify the direct impact of IRGC-backed groups on regional stability and international relations. This extension of power has often been at odds with U.S. interests in the region, leading to heightened tensions and confrontations. The IRGC's actions, seen by the U.S. as state-sponsored support for terrorism, have resulted in significant sanctions against Iran and have been a persistent obstacle to thawing U.S.-Iran relations.

In the volatile confluence of Middle Eastern politics, the power of cinematic portrayl and oil resources in Iran's international relations underscores a multifaceted foreign policy, influencing nuclear talks and shaping a complex framework for national security in the face of global tensions.

The 1953 CIA-assisted overthrow in Iran, sanctioned by President Eisenhower, marked a tectonic shift in Iran-U.S. relations, supplanting America's image from an admired non-colonial power to a domineering force indistinguishable from historic colonial powers. This dramatic reversal of sentiment, solidified by the 1979 U.S. embassy hostage crisis, has entrenched a mutual distrust that has determined diplomatic relations to this day. This tumultuous historical context was crucial in shaping Iran's modern identity, a narrative that persisted as Ayatollah Ruhollah Khomeini, combating the "westoxification" of Iran, dramatically altered the nation's trajectory in 1979 by displacing the Pahlavi dynasty and instituting the Islamic Republic of Iran, a move that substantially reconfigured Iran's religious, political, and social fabric. This continuum of transformation underscores Iran's evolving identity and international relations, embedded in a history of struggle and adaptation.

The 1979 Iranian Revolution, which ushered in Ayatollah Khomeini's Islamic Republic---the first of its kind via popular revolution---drastically shifted Iran's socio-cultural fabric and geopolitical standing, leading to enduring regional instability and increased U.S. involvement. As Khomeini rose to power on the back of widespread disaffection with the Pahlavi regime, he rapidly consolidated power, sidelining any opposition to his conservative Islamic governance. This historical backdrop is artfully echoed in cinema, with films like "The Host" and "A Girl Walks Home Alone at Night" reflecting Iran's transformative struggle through potent themes of identity and resistance, encapsulating the nation's reconstructed identity and the ensuing tensions in U.S.-Iranian relations, marred by anti-American sentiment.

"The Host" metaphorically portrays the impact of the revolution through its anti-establishment themes, paralleling the Shah's disconnect with Iranian society. "A Girl Walks Home Alone at Night," on the other hand, delves into the gender dynamics of post-revolution Iran, drawing parallels with the women's rights movement against the mandatory hijab. The protagonist's autonomy challenges the narrative of oppression and signifies the internal conflict within Iran regarding women's liberties, a struggle that continues to influence its international image and relations, particularly in light of Iran's commitments to international human rights frameworks.

While the films reflect the internal dynamics of Iran, they also have broader implications for its foreign relations. The portrayal of women's rights, or the lack thereof, in these films, feeds into the international discourse on Iran, affecting its global standing and diplomatic interactions. Iran's adherence, or perceived lack of adherence, to international human rights standards, especially regarding gender equality, remains a contentious point in its dealings with other nations. As such, the cultural representations in these films are not merely for domestic consumption but serve as a commentary on Iran's place in the world---a place fraught with the complexities of balancing traditional values with the pressures of modernity and human rights obligations.

This cultural narrative dovetails with the European Union's recent actions; the EU's imposition of restrictive measures on Iranian individuals and entities, including prominent government and security figures, due to human rights violations, significantly strains Iran's foreign relations with the EU and the broader international community. By freezing assets, banning travel, and restricting the export of potentially repressive technology to Iran, the EU conveys a strong disapproval of Iran's internal policies, particularly the harsh crackdown on protests and the suppression of freedom of expression. This response to Iran's handling of the protests following Mahsa Amini's death not only impacts diplomatic ties but also places economic and political pressure on Tehran to reform its approach to human rights and due process. Such sanctions reinforce the EU's commitment to human rights and may influence Iran's international standing, potentially leading to isolation or incentivizing policy changes to restore relations.

Iran's socio-cultural evolution following the 1979 Revolution has had enduring implications for its foreign policy and national security framework. The transition from secularism to a politically-religious governance profoundly impacted women's societal roles, igniting domestic opposition that eventually pressured the regime to reverse its stance on female education---a move indicative of the regime's sensitivity to internal dissent. This domestic upheaval contributed to the creation of a pervasive anti-American sentiment stemming from perceived U.S. interference, has colored Iran's diplomatic engagements. The post-revolutionary identity crisis, exacerbated by events such as the U.S. embassy hostage situation, portrayed by Khomeini as a second revolution, has deeply influenced Iran's approach to international relations, promoting a stance of resistance and self-reliance against Western powers. This narrative of resistance, reflected culturally in films like "The Host," echoes through Iran's foreign policy as it navigates a complex interplay of upholding traditional values while countering foreign influence.

The symbolic narrative of "The Host," where Western intervention manifests in ecological disaster, parallels Iran's sociocultural injustice that culminated in the 1979 Revolution. The Shah's close ties with the U.S., perceived as a catalyst for unwelcome Western influence, spurred a societal backlash against policies deemed antithetical to Iran's traditional and religious values. This internal struggle against Westernization has since been a cornerstone of Iran's foreign policy, framing its approach to national security with a wary stance towards Western involvement, striving to safeguard its cultural integrity while navigating the geopolitical pressures imposed by global power dynamics.

​​The allegory of foreign control in "The Host" reflects Iran's historic struggle for sovereignty over its resources, particularly oil, which has been central to its foreign policy and a focal point in relations with Western powers. The 1951 nationalization of its oil industry symbolized Iran's assertion of autonomy, catalyzing the 1953 coup and underscoring the strategic yet vulnerable position oil occupies in Iran's international dynamics, granting Tehran considerable influence in global markets.

In the 1970s, the strategic landscape of the Middle East underwent a profound transformation due to the oil revolution, significantly impacting U.S. foreign relations and security policy in the region. The British withdrawal from the Gulf in 1971 coincided with the peak of U.S. engagement in Vietnam, limiting Washington's appetite for direct military commitments. Instead, the U.S. pivoted to a strategy of empowering local allies, Iran and Saudi Arabia, as bulwarks against Soviet influence and as part of its 'twin-pillar' policy. The 1973 Arab oil embargo, led by Saudi Arabia in response to U.S. support for Israel, seemingly threatened this policy but paradoxically ended up reinforcing it. Iran capitalized on the situation, driving oil prices to unprecedented highs, which inadvertently bolstered the economic and military significance of the U.S.'s Gulf allies.

The surge in oil prices, from roughly \$3 to over \$12 per barrel, not only precipitated a global recession but also underscored the Gulf's critical importance to U.S. foreign policy---a reality underscored by Iran's newfound wealth and its subsequent arms purchases from the U.S. Despite the economic strain, this period saw an intensification of U.S. military, economic, and political ties with Iran and Saudi Arabia, albeit with a noted absence of direct military involvement by the U.S. in the Gulf. The oil revolution thus solidified the Gulf's centrality to global energy markets and U.S. security considerations, with Iranian oil revenues fueling both regional military capacities and Washington's strategic imperatives, framing a complex interdependence that continues to influence foreign relations and security policies today.

Iran's clout in global oil markets is a key driver of its international influence. In recent years, the sector's significance has been highlighted by major investors, including Warren Buffett, whose continued investments underscore its ongoing relevance. As a primary oil supplier, particularly to China, Iran wields considerable geopolitical leverage. Yet, this influence is vulnerable to international events and policy shifts, such as the U.S.'s intensified scrutiny amid tensions with Israel, which could restrict its oil exports. Amidst a global shift toward renewable energy, Iran's strategic use of oil in its foreign policy remains a critical factor, solidifying its role in both regional and international arenas.

Iran's oil reserves, a cornerstone of its economy and a major factor in its foreign policy, have been central to the country's negotiations on the international stage, particularly during the nuclear talks that led to the Joint Comprehensive Plan of Action (JCPOA). The protracted nuclear negotiations, occurring concurrently with the counter-ISIS campaign, underscored the strategic importance of Iran's oil in both bargaining and security contexts. Europe's interest in resolving the nuclear issue was not only to limit nuclear proliferation but also to facilitate broader engagement with Iran, encompassing regional security and human rights concerns.

The JCPOA, seen as a thaw in Iran-U.S. relations under Obama, was short-lived, with subsequent U.S. administrations adopting hardline stances, including the "maximum pressure" campaign, which ignored the complexities of Iran's regional ambitions and security imperatives, particularly in the Persian Gulf. Iran's response to these pressures, including the symbolic display of military capabilities, was a clear message of deterrence, signaling its readiness to protect its interests and prevent historical aggressions from repeating.

Amidst these tensions, Iran's oil continues to serve as leverage, granting it economic and political influence while also being a vulnerability subject to international sanctions and diplomatic maneuvers. The country's Shi'a ideology post-revolution has further colored its foreign policy, utilizing religious affinities to strengthen ties with Shi'a actors and counterbalance Sunni-majority nations. These elements form a complex matrix within Iran's foreign policy, where oil resources, ideological commitments, and security concerns are inextricably linked, influencing Iran's interactions with global powers and shaping the security policies of the Middle East.

A more nuanced understanding of Iran's perspective, informed by its historical experiences and ideological commitments, is essential for any meaningful progress in foreign relations and for ensuring regional security. This strategic depth, where oil wealth underpins Iran's economic and diplomatic engagements, remains a key aspect of its national security posture and foreign policy calculations.

\
\

Works Cited 

Amanat, Abbas, and Bill Nelson. Iran : a Modern History. New Haven, CT: Yale University Press, 2017.

Amirpour, Ana Lily, dir. 2014. A Girl Walks Home Alone at Night. \[Film screening\] Halloween Film 'Screaming', organized by GW Foreign Film Society & Iranian Students Association, University Student Center Room 405, October 26th, 2023.

Azodi, Sina. "It's Been 70 yrs Since the CIA-Assisted Coup in Iran." Responsible Statecraft. August 16, 2023.<https://responsiblestatecraft.org/2023/08/16/its-been-70-yrs-since-the-cia-assisted-coup-in-iran/>.

Babaie, Sussan. Isfahan and Its Palaces : Statecraft, Shi'ism and the Architecture of Conviviality in Early Modern Iran. Edinburgh, Scotland: Edinburgh University Press, 2022.

Bong, Joon-ho, dir. 2006. The Host. Performed by Song Kang-ho, Byun Hee-bong, Park Hae-il, and Go Ah-sung. South Korea: Showbox Entertainment. Netflix.

Bayandor, Darioush. The Shah, the Islamic Revolution and the United States. 1st ed. 2019. Cham: Springer International Publishing, 2019.

​​Chen, Aizhu, and Muyu Xu. "China Saves Billions of Dollars on Record Sanctioned Oil Imports." Reuters. October 11, 2023.<https://www.reuters.com/markets/commodities/china-saves-billions-dollars-record-sanctioned-oil-imports-2023-10-11/>.

Council of the European Union. "Iran: EU Adopts Further Restrictive Measures Against Human Rights Violations." Consilium Europa. January 23, 2023.<https://www.consilium.europa.eu/en/press/press-releases/2023/01/23/iran-eu-adopts-further-restrictive-measures-against-human-rights-violations/>.

Fawcett, Louise. International Relations of the Middle East. 5th ed. Oxford: Oxford University Press Academic UK, 2019. VitalSource Bookshelf.

Gause, F. Gregory. The International Relations of the Persian Gulf. Cambridge: Cambridge University Press, 2010.

​​"Iranian women - before and after the Islamic Revolution" BBC News. January 29, 2019.<https://www.bbc.com/news/world-middle-east-47032829>.

Kang, Woosung. "A Fantasy of Survival and Class Stink in Parasite." UNITAS 95, no. 3 (2022): 189--212. [https://doi.org/10.31944/2022950206. ](https://doi.org/10.31944/2022950206.)

Kostiner, Joseph. The GCC States and the Security Challenges of the Twenty-First Century. Ramat Gan: Begin-Sadat Center for Strategic Studies, Bar-Ilan University, 2010.

Khosroshahi, Zahra. "Iran's Culture of Horror." Foreign Policy. Last modified October 30, 2021. Accessed October 29, 2023.[https://foreignpolicy.com/2021/10/30/iran-culture-horror-film-a-girl-walks-home-alone-at-night/.](https://foreignpolicy.com/2021/10/30/iran-culture-horror-film-a-girl-walks-home-alone-at-night/)

Maloney, Suzanne. "1979: Iran and America." Brookings. Accessed October 29, 2023.[https://www.brookings.edu/articles/1979-iran-and-america/.](https://www.brookings.edu/articles/1979-iran-and-america/)

Nereim, Vivian and Saeed Al-Batati. "Yemen's Houthi Militia Targets Israel in Missile Attack." The New York Times, October 31, 2023.

Otani, Akane. ​​"Warren Buffett Oil Stocks Berkshire Hathaway Charlie Munger." The Wall Street Journal. Accessed 1 Nov. 2023.<https://www.wsj.com/articles/warren-buffett-oil-stocks-berkshire-hathaway-charlie-munger-2c8b12b8>.

Shahram Akbarzadeh, Zahid Shahab Ahmed & Niamatullah Ibrahimi (2023) Soft power, hard power dynamics: the case of Iran in Afghanistan, British Journal of Middle Eastern Studies, 50:1, 67-86, DOI: [10.1080/13530194.2021.1928479](https://doi-org.proxygw.wrlc.org/10.1080/13530194.2021.1928479)

Tabatabai, Ariane M., 'The Revolution Expands', No Conquest, No Defeat: Iran's National Security Strategy (2020; online edn, Oxford Academic, 21 Jan. 2021), <https://doi.org/10.1093/oso/9780197534601.003.0008>, accessed 1 Nov. 2023.

Thaler, David E. Mullahs, Guards, and Bonyads an Exploration of Iranian Leadership Dynamics. Santa Monica, CA: RAND, 2010.

\
